{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import os, pathlib, math\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from import_clean import *\n",
    "from calculate import *\n",
    "from itertools import combinations\n",
    "from tqdm.notebook import tqdm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts009-utla.csv not found in data/census2021-ts009\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts012-utla.csv not found in data/census2021-ts012\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts013-utla.csv not found in data/census2021-ts013\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts022-utla.csv not found in data/census2021-ts022\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts024-utla.csv not found in data/census2021-ts024\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts028-utla.csv not found in data/census2021-ts028\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts031-utla.csv not found in data/census2021-ts031\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts032-utla.csv not found in data/census2021-ts032\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts033-utla.csv not found in data/census2021-ts033\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts034-utla.csv not found in data/census2021-ts034\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts035-utla.csv not found in data/census2021-ts035\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts036-utla.csv not found in data/census2021-ts036\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts076-utla.csv not found in data/census2021-ts076\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts062-utla.csv not found in data/census2021-ts062\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts064-utla.csv not found in data/census2021-ts064\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts047-utla.csv not found in data/census2021-ts047\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts079-utla.csv not found in data/census2021-ts079\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts070-utla.csv not found in data/census2021-ts070\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts037asp-utla.csv not found in data/census2021-ts037asp\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts038asp-utla.csv not found in data/census2021-ts038asp\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n",
      "c:\\Users\\timko\\Documents\\work_experience_notebooks\\import_clean.py:107: UserWarning: File census2021-ts039asp-utla.csv not found in data/census2021-ts039asp\n",
      "  warnings.warn(f\"File {folder}-{region}.csv not found in data/{folder}\")\n"
     ]
    }
   ],
   "source": [
    "all_data = cleanup_all(import_all_data(\"utla\"), remove_geography_code=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "coefficients = pd.DataFrame(columns=['variable1', 'variable2', 'coefficient'])\n",
    "keys = list(all_data.keys())\n",
    "keys.remove(\"TS006\")\n",
    "keys.remove(\"TS008\")\n",
    "keys.remove(\"TS020\")\n",
    "keys.remove(\"TS041\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Code</th>\n",
       "      <th>Count</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>TS006</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>TS008</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>TS020</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>TS041</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Code Count\n",
       "0  TS006     0\n",
       "0  TS008     0\n",
       "0  TS020     0\n",
       "0  TS041     0"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "nonstandard = pd.DataFrame(columns=['Code', 'Count'])\n",
    "for dfCode in list(all_data.keys()):\n",
    "    if len([column for column in list(all_data[dfCode].columns) if \"Total\" in column]) != 1:\n",
    "        nonstandard = pd.concat([nonstandard, pd.DataFrame({'Code': dfCode, 'Count': len([column for column in list(all_data[dfCode].columns) if \"Total\" in column])}, index=[0])])\n",
    "nonstandard"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "e8826ad170d54b08a990fa10b2a1f953",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/1326.0 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "c:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\numpy\\lib\\function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    }
   ],
   "source": [
    "length = math.factorial(len(keys)) / (math.factorial(2) * math.factorial(len(keys) - 2))\n",
    "for k1, k2 in tqdm(combinations(keys, 2), total=length):\n",
    "    dataframes = [all_data[k1], all_data[k2]]\n",
    "    columns = [[column for column in df.columns if column != \"geography code\" and \"Total\" not in column] for df in dataframes]\n",
    "    totals = [[column for column in df.columns if \"Total\" in column][0] for df in dataframes]\n",
    "    #fig, ax = plt.subplots(len(columns[0]), len(columns[1]), figsize=(10*len(columns[0]), 5*len(columns[1])))\n",
    "    df_merged = dataframes[0].merge(dataframes[1], on=\"geography code\")\n",
    "    for column_set, total in zip(columns, totals):\n",
    "        df_merged[column_set] = df_merged[column_set].divide(df_merged[total], axis=0)\n",
    "    for i, column1 in enumerate(columns[0]):\n",
    "        for j, column2 in enumerate(columns[1]):\n",
    "            x, y = df_merged[column1], df_merged[column2]\n",
    "            pearsons = np.corrcoef(np.array(x), np.array(y))[0][1]\n",
    "            coefficients = pd.concat([coefficients, pd.DataFrame({\"variable1\": column1, \"variable2\": column2, \"coefficient\": pearsons}, index=[0])])\n",
    "            #sns.scatterplot(df_merged, x=x, y=y, ax=ax[i, j]).set(title=f\"{column1} vs {column2} (Pearson's: {pearsons})\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "cannot reindex on an axis with duplicate labels",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[11], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m fig, ax \u001b[39m=\u001b[39m plt\u001b[39m.\u001b[39msubplots(figsize\u001b[39m=\u001b[39m(\u001b[39m10\u001b[39m, \u001b[39m10\u001b[39m))\n\u001b[1;32m----> 2\u001b[0m sns\u001b[39m.\u001b[39;49mhistplot(data\u001b[39m=\u001b[39;49mcoefficients, x\u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39mcoefficient\u001b[39;49m\u001b[39m'\u001b[39;49m, ax\u001b[39m=\u001b[39;49max, bins\u001b[39m=\u001b[39;49m\u001b[39m50\u001b[39;49m, stat\u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39mdensity\u001b[39;49m\u001b[39m'\u001b[39;49m, kde\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m)\n",
      "File \u001b[1;32mc:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\seaborn\\distributions.py:1432\u001b[0m, in \u001b[0;36mhistplot\u001b[1;34m(data, x, y, hue, weights, stat, bins, binwidth, binrange, discrete, cumulative, common_bins, common_norm, multiple, element, fill, shrink, kde, kde_kws, line_kws, thresh, pthresh, pmax, cbar, cbar_ax, cbar_kws, palette, hue_order, hue_norm, color, log_scale, legend, ax, **kwargs)\u001b[0m\n\u001b[0;32m   1421\u001b[0m estimate_kws \u001b[39m=\u001b[39m \u001b[39mdict\u001b[39m(\n\u001b[0;32m   1422\u001b[0m     stat\u001b[39m=\u001b[39mstat,\n\u001b[0;32m   1423\u001b[0m     bins\u001b[39m=\u001b[39mbins,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1427\u001b[0m     cumulative\u001b[39m=\u001b[39mcumulative,\n\u001b[0;32m   1428\u001b[0m )\n\u001b[0;32m   1430\u001b[0m \u001b[39mif\u001b[39;00m p\u001b[39m.\u001b[39munivariate:\n\u001b[1;32m-> 1432\u001b[0m     p\u001b[39m.\u001b[39;49mplot_univariate_histogram(\n\u001b[0;32m   1433\u001b[0m         multiple\u001b[39m=\u001b[39;49mmultiple,\n\u001b[0;32m   1434\u001b[0m         element\u001b[39m=\u001b[39;49melement,\n\u001b[0;32m   1435\u001b[0m         fill\u001b[39m=\u001b[39;49mfill,\n\u001b[0;32m   1436\u001b[0m         shrink\u001b[39m=\u001b[39;49mshrink,\n\u001b[0;32m   1437\u001b[0m         common_norm\u001b[39m=\u001b[39;49mcommon_norm,\n\u001b[0;32m   1438\u001b[0m         common_bins\u001b[39m=\u001b[39;49mcommon_bins,\n\u001b[0;32m   1439\u001b[0m         kde\u001b[39m=\u001b[39;49mkde,\n\u001b[0;32m   1440\u001b[0m         kde_kws\u001b[39m=\u001b[39;49mkde_kws,\n\u001b[0;32m   1441\u001b[0m         color\u001b[39m=\u001b[39;49mcolor,\n\u001b[0;32m   1442\u001b[0m         legend\u001b[39m=\u001b[39;49mlegend,\n\u001b[0;32m   1443\u001b[0m         estimate_kws\u001b[39m=\u001b[39;49mestimate_kws,\n\u001b[0;32m   1444\u001b[0m         line_kws\u001b[39m=\u001b[39;49mline_kws,\n\u001b[0;32m   1445\u001b[0m         \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs,\n\u001b[0;32m   1446\u001b[0m     )\n\u001b[0;32m   1448\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m   1450\u001b[0m     p\u001b[39m.\u001b[39mplot_bivariate_histogram(\n\u001b[0;32m   1451\u001b[0m         common_bins\u001b[39m=\u001b[39mcommon_bins,\n\u001b[0;32m   1452\u001b[0m         common_norm\u001b[39m=\u001b[39mcommon_norm,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1462\u001b[0m         \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs,\n\u001b[0;32m   1463\u001b[0m     )\n",
      "File \u001b[1;32mc:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\seaborn\\distributions.py:430\u001b[0m, in \u001b[0;36m_DistributionPlotter.plot_univariate_histogram\u001b[1;34m(self, multiple, element, fill, common_norm, common_bins, shrink, kde, kde_kws, color, legend, line_kws, estimate_kws, **plot_kws)\u001b[0m\n\u001b[0;32m    427\u001b[0m histograms \u001b[39m=\u001b[39m {}\n\u001b[0;32m    429\u001b[0m \u001b[39m# Do pre-compute housekeeping related to multiple groups\u001b[39;00m\n\u001b[1;32m--> 430\u001b[0m all_data \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mcomp_data\u001b[39m.\u001b[39mdropna()\n\u001b[0;32m    431\u001b[0m all_weights \u001b[39m=\u001b[39m all_data\u001b[39m.\u001b[39mget(\u001b[39m\"\u001b[39m\u001b[39mweights\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mNone\u001b[39;00m)\n\u001b[0;32m    433\u001b[0m multiple_histograms \u001b[39m=\u001b[39m \u001b[39mset\u001b[39m(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mvariables) \u001b[39m-\u001b[39m {\u001b[39m\"\u001b[39m\u001b[39mx\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39m\"\u001b[39m\u001b[39my\u001b[39m\u001b[39m\"\u001b[39m}\n",
      "File \u001b[1;32mc:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\seaborn\\_oldcore.py:1134\u001b[0m, in \u001b[0;36mVectorPlotter.comp_data\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   1132\u001b[0m         \u001b[39melse\u001b[39;00m:\n\u001b[0;32m   1133\u001b[0m             comp_col \u001b[39m=\u001b[39m pd\u001b[39m.\u001b[39mSeries(dtype\u001b[39m=\u001b[39m\u001b[39mfloat\u001b[39m, name\u001b[39m=\u001b[39mvar)\n\u001b[1;32m-> 1134\u001b[0m         comp_data\u001b[39m.\u001b[39;49minsert(\u001b[39m0\u001b[39;49m, var, comp_col)\n\u001b[0;32m   1136\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_comp_data \u001b[39m=\u001b[39m comp_data\n\u001b[0;32m   1138\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_comp_data\n",
      "File \u001b[1;32mc:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\pandas\\core\\frame.py:4776\u001b[0m, in \u001b[0;36mDataFrame.insert\u001b[1;34m(self, loc, column, value, allow_duplicates)\u001b[0m\n\u001b[0;32m   4773\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39misinstance\u001b[39m(loc, \u001b[39mint\u001b[39m):\n\u001b[0;32m   4774\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mTypeError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39mloc must be int\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m-> 4776\u001b[0m value \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_sanitize_column(value)\n\u001b[0;32m   4777\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_mgr\u001b[39m.\u001b[39minsert(loc, column, value)\n",
      "File \u001b[1;32mc:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\pandas\\core\\frame.py:4867\u001b[0m, in \u001b[0;36mDataFrame._sanitize_column\u001b[1;34m(self, value)\u001b[0m\n\u001b[0;32m   4865\u001b[0m     \u001b[39mreturn\u001b[39;00m _reindex_for_setitem(value, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mindex)\n\u001b[0;32m   4866\u001b[0m \u001b[39melif\u001b[39;00m is_dict_like(value):\n\u001b[1;32m-> 4867\u001b[0m     \u001b[39mreturn\u001b[39;00m _reindex_for_setitem(Series(value), \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mindex)\n\u001b[0;32m   4869\u001b[0m \u001b[39mif\u001b[39;00m is_list_like(value):\n\u001b[0;32m   4870\u001b[0m     com\u001b[39m.\u001b[39mrequire_length_match(value, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mindex)\n",
      "File \u001b[1;32mc:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\pandas\\core\\frame.py:11615\u001b[0m, in \u001b[0;36m_reindex_for_setitem\u001b[1;34m(value, index)\u001b[0m\n\u001b[0;32m  11611\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mValueError\u001b[39;00m \u001b[39mas\u001b[39;00m err:\n\u001b[0;32m  11612\u001b[0m     \u001b[39m# raised in MultiIndex.from_tuples, see test_insert_error_msmgs\u001b[39;00m\n\u001b[0;32m  11613\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m value\u001b[39m.\u001b[39mindex\u001b[39m.\u001b[39mis_unique:\n\u001b[0;32m  11614\u001b[0m         \u001b[39m# duplicate axis\u001b[39;00m\n\u001b[1;32m> 11615\u001b[0m         \u001b[39mraise\u001b[39;00m err\n\u001b[0;32m  11617\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mTypeError\u001b[39;00m(\n\u001b[0;32m  11618\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mincompatible index of inserted column with frame index\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m  11619\u001b[0m     ) \u001b[39mfrom\u001b[39;00m \u001b[39merr\u001b[39;00m\n\u001b[0;32m  11620\u001b[0m \u001b[39mreturn\u001b[39;00m reindexed_value\n",
      "File \u001b[1;32mc:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\pandas\\core\\frame.py:11610\u001b[0m, in \u001b[0;36m_reindex_for_setitem\u001b[1;34m(value, index)\u001b[0m\n\u001b[0;32m  11608\u001b[0m \u001b[39m# GH#4107\u001b[39;00m\n\u001b[0;32m  11609\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m> 11610\u001b[0m     reindexed_value \u001b[39m=\u001b[39m value\u001b[39m.\u001b[39;49mreindex(index)\u001b[39m.\u001b[39m_values\n\u001b[0;32m  11611\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mValueError\u001b[39;00m \u001b[39mas\u001b[39;00m err:\n\u001b[0;32m  11612\u001b[0m     \u001b[39m# raised in MultiIndex.from_tuples, see test_insert_error_msmgs\u001b[39;00m\n\u001b[0;32m  11613\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m value\u001b[39m.\u001b[39mindex\u001b[39m.\u001b[39mis_unique:\n\u001b[0;32m  11614\u001b[0m         \u001b[39m# duplicate axis\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\pandas\\core\\series.py:4918\u001b[0m, in \u001b[0;36mSeries.reindex\u001b[1;34m(self, index, axis, method, copy, level, fill_value, limit, tolerance)\u001b[0m\n\u001b[0;32m   4901\u001b[0m \u001b[39m@doc\u001b[39m(\n\u001b[0;32m   4902\u001b[0m     NDFrame\u001b[39m.\u001b[39mreindex,  \u001b[39m# type: ignore[has-type]\u001b[39;00m\n\u001b[0;32m   4903\u001b[0m     klass\u001b[39m=\u001b[39m_shared_doc_kwargs[\u001b[39m\"\u001b[39m\u001b[39mklass\u001b[39m\u001b[39m\"\u001b[39m],\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   4916\u001b[0m     tolerance\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m,\n\u001b[0;32m   4917\u001b[0m ) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m Series:\n\u001b[1;32m-> 4918\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39msuper\u001b[39;49m()\u001b[39m.\u001b[39;49mreindex(\n\u001b[0;32m   4919\u001b[0m         index\u001b[39m=\u001b[39;49mindex,\n\u001b[0;32m   4920\u001b[0m         method\u001b[39m=\u001b[39;49mmethod,\n\u001b[0;32m   4921\u001b[0m         copy\u001b[39m=\u001b[39;49mcopy,\n\u001b[0;32m   4922\u001b[0m         level\u001b[39m=\u001b[39;49mlevel,\n\u001b[0;32m   4923\u001b[0m         fill_value\u001b[39m=\u001b[39;49mfill_value,\n\u001b[0;32m   4924\u001b[0m         limit\u001b[39m=\u001b[39;49mlimit,\n\u001b[0;32m   4925\u001b[0m         tolerance\u001b[39m=\u001b[39;49mtolerance,\n\u001b[0;32m   4926\u001b[0m     )\n",
      "File \u001b[1;32mc:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\pandas\\core\\generic.py:5360\u001b[0m, in \u001b[0;36mNDFrame.reindex\u001b[1;34m(self, labels, index, columns, axis, method, copy, level, fill_value, limit, tolerance)\u001b[0m\n\u001b[0;32m   5357\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_reindex_multi(axes, copy, fill_value)\n\u001b[0;32m   5359\u001b[0m \u001b[39m# perform the reindex on the axes\u001b[39;00m\n\u001b[1;32m-> 5360\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_reindex_axes(\n\u001b[0;32m   5361\u001b[0m     axes, level, limit, tolerance, method, fill_value, copy\n\u001b[0;32m   5362\u001b[0m )\u001b[39m.\u001b[39m__finalize__(\u001b[39mself\u001b[39m, method\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mreindex\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\pandas\\core\\generic.py:5375\u001b[0m, in \u001b[0;36mNDFrame._reindex_axes\u001b[1;34m(self, axes, level, limit, tolerance, method, fill_value, copy)\u001b[0m\n\u001b[0;32m   5372\u001b[0m     \u001b[39mcontinue\u001b[39;00m\n\u001b[0;32m   5374\u001b[0m ax \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_get_axis(a)\n\u001b[1;32m-> 5375\u001b[0m new_index, indexer \u001b[39m=\u001b[39m ax\u001b[39m.\u001b[39;49mreindex(\n\u001b[0;32m   5376\u001b[0m     labels, level\u001b[39m=\u001b[39;49mlevel, limit\u001b[39m=\u001b[39;49mlimit, tolerance\u001b[39m=\u001b[39;49mtolerance, method\u001b[39m=\u001b[39;49mmethod\n\u001b[0;32m   5377\u001b[0m )\n\u001b[0;32m   5379\u001b[0m axis \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_get_axis_number(a)\n\u001b[0;32m   5380\u001b[0m obj \u001b[39m=\u001b[39m obj\u001b[39m.\u001b[39m_reindex_with_indexers(\n\u001b[0;32m   5381\u001b[0m     {axis: [new_index, indexer]},\n\u001b[0;32m   5382\u001b[0m     fill_value\u001b[39m=\u001b[39mfill_value,\n\u001b[0;32m   5383\u001b[0m     copy\u001b[39m=\u001b[39mcopy,\n\u001b[0;32m   5384\u001b[0m     allow_dups\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m,\n\u001b[0;32m   5385\u001b[0m )\n",
      "File \u001b[1;32mc:\\Users\\timko\\miniconda3\\envs\\geo_env\\Lib\\site-packages\\pandas\\core\\indexes\\base.py:4275\u001b[0m, in \u001b[0;36mIndex.reindex\u001b[1;34m(self, target, method, level, limit, tolerance)\u001b[0m\n\u001b[0;32m   4272\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39mcannot handle a non-unique multi-index!\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m   4273\u001b[0m \u001b[39melif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mis_unique:\n\u001b[0;32m   4274\u001b[0m     \u001b[39m# GH#42568\u001b[39;00m\n\u001b[1;32m-> 4275\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39mcannot reindex on an axis with duplicate labels\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m   4276\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m   4277\u001b[0m     indexer, _ \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mget_indexer_non_unique(target)\n",
      "\u001b[1;31mValueError\u001b[0m: cannot reindex on an axis with duplicate labels"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA08AAAMtCAYAAABHAkpLAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAAAqn0lEQVR4nO3df2zX9Z3A8Vel0OoGX5mMVrRK9QxI0ERLRLh0usQVcP66cRnq7O0Wz5MsDoEsiroLRBNQZ5wx+OPGcLclO/U2xOMPjoDnJJ4UFQPKKTPZDoVTKsKw5eaOn5/7w6OxttRXtV+L8ngk3z/6+b7f377f9pPGJ59+P9+KoiiKAAAAoEfH9PcCAAAAPg/EEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAICEyv5eQH84ePBgvP322zF48OCoqKjo7+UAAAD9pCiK2L17d4wYMSKOOabna0tHZTy9/fbbUVdX19/LAAAAjhBbt26Nk08+uccxR2U8DR48OCI++A80ZMiQfl4NAADQX9rb26Ourq6jEXpyVMbToT/VGzJkiHgCAABSb+dxwwgAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLKHk8PPvhg1NfXR3V1dTQ0NMSzzz7b4/jVq1dHQ0NDVFdXx2mnnRYPP/zwYcc+9thjUVFREVdccUUfrxoAAKCzssbT448/HjNnzozbbrst1q9fH42NjTFlypTYsmVLt+M3b94cF198cTQ2Nsb69evj1ltvjRkzZsSSJUu6jH3zzTfjhz/8YTQ2NpZzCwAAABERUVEURVGuFx8/fnyce+658dBDD3UcO/PMM+OKK66IBQsWdBl/8803x7Jly2LTpk0dx6ZPnx4vv/xytLS0dBw7cOBAXHDBBfG9730vnn322XjvvffiySefPOw69uzZE3v27On4ur29Perq6qKtrS2GDBnyKXcJAAB8XrW3t0epVEq1QdmuPO3duzdeeumlaGpq6nS8qakp1qxZ0+2clpaWLuMnTZoU69ati3379nUcu/322+OrX/1qXHvttam1LFiwIEqlUsejrq6ul7sBAACOdmWLpx07dsSBAweipqam0/GamppobW3tdk5ra2u34/fv3x87duyIiIjnnnsuFi9eHIsWLUqv5ZZbbom2traOx9atW3u5GwAA4GhXWe5vUFFR0enroii6HPu48YeO7969O6655ppYtGhRDBs2LL2GqqqqqKqq6sWqAQAAOitbPA0bNiwGDBjQ5SrT9u3bu1xdOqS2trbb8ZWVlXHCCSfEq6++Gm+88UZceumlHc8fPHgwIiIqKyvj9ddfj9NPP72PdwIAAFDGP9sbNGhQNDQ0xKpVqzodX7VqVUycOLHbORMmTOgyfuXKlTFu3LgYOHBgjB49OjZu3BgbNmzoeFx22WXx9a9/PTZs2OC9TAAAQNmU9c/2Zs+eHc3NzTFu3LiYMGFC/PSnP40tW7bE9OnTI+KD9yK99dZb8ctf/jIiPriz3sKFC2P27Nlx3XXXRUtLSyxevDgeffTRiIiorq6OsWPHdvoexx9/fEREl+MAAAB9qazxNG3atNi5c2fcfvvtsW3bthg7dmwsX748Tj311IiI2LZtW6fPfKqvr4/ly5fHrFmz4oEHHogRI0bE/fffH1OnTi3nMgEAAD5WWT/n6UjVm3u5AwAAX1xHxOc8AQAAfJGIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSUPZ4efPDBqK+vj+rq6mhoaIhnn322x/GrV6+OhoaGqK6ujtNOOy0efvjhTs8vWrQoGhsbY+jQoTF06NC46KKL4oUXXijnFgAAAMobT48//njMnDkzbrvttli/fn00NjbGlClTYsuWLd2O37x5c1x88cXR2NgY69evj1tvvTVmzJgRS5Ys6RjzzDPPxFVXXRW//e1vo6WlJU455ZRoamqKt956q5xbAQAAjnIVRVEU5Xrx8ePHx7nnnhsPPfRQx7EzzzwzrrjiiliwYEGX8TfffHMsW7YsNm3a1HFs+vTp8fLLL0dLS0u33+PAgQMxdOjQWLhwYfzN3/xNt2P27NkTe/bs6fi6vb096urqoq2tLYYMGfJJtwcAAHzOtbe3R6lUSrVB2a487d27N1566aVoamrqdLypqSnWrFnT7ZyWlpYu4ydNmhTr1q2Lffv2dTvn/fffj3379sVXvvKVw65lwYIFUSqVOh51dXW93A0AAHC0K1s87dixIw4cOBA1NTWdjtfU1ERra2u3c1pbW7sdv3///tixY0e3c+bMmRMnnXRSXHTRRYddyy233BJtbW0dj61bt/ZyNwAAwNGustzfoKKiotPXRVF0OfZx47s7HhFx9913x6OPPhrPPPNMVFdXH/Y1q6qqoqqqqjfLBgAA6KRs8TRs2LAYMGBAl6tM27dv73J16ZDa2tpux1dWVsYJJ5zQ6fg999wT8+fPj6eeeirOPvvsvl08AADAR5Ttz/YGDRoUDQ0NsWrVqk7HV61aFRMnTux2zoQJE7qMX7lyZYwbNy4GDhzYcezHP/5x3HHHHbFixYoYN25c3y8eAADgI8p6q/LZs2fHz372s3jkkUdi06ZNMWvWrNiyZUtMnz49Ij54L9KH75A3ffr0ePPNN2P27NmxadOmeOSRR2Lx4sXxwx/+sGPM3XffHT/60Y/ikUceiZEjR0Zra2u0trbG//zP/5RzKwAAwFGurO95mjZtWuzcuTNuv/322LZtW4wdOzaWL18ep556akREbNu2rdNnPtXX18fy5ctj1qxZ8cADD8SIESPi/vvvj6lTp3aMefDBB2Pv3r3x13/9152+19y5c2PevHnl3A4AAHAUK+vnPB2penMvdwAA4IvriPicJwAAgC8S8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAICEssfTgw8+GPX19VFdXR0NDQ3x7LPP9jh+9erV0dDQENXV1XHaaafFww8/3GXMkiVLYsyYMVFVVRVjxoyJpUuXlmv5AAAAEVHmeHr88cdj5syZcdttt8X69eujsbExpkyZElu2bOl2/ObNm+Piiy+OxsbGWL9+fdx6660xY8aMWLJkSceYlpaWmDZtWjQ3N8fLL78czc3N8e1vfzuef/75cm4FAAA4ylUURVGU68XHjx8f5557bjz00EMdx84888y44oorYsGCBV3G33zzzbFs2bLYtGlTx7Hp06fHyy+/HC0tLRERMW3atGhvb49/+7d/6xgzefLkGDp0aDz66KPdrmPPnj2xZ8+ejq/b29ujrq4u2traYsiQIZ96nwAAwOdTe3t7lEqlVBuU7crT3r1746WXXoqmpqZOx5uammLNmjXdzmlpaekyftKkSbFu3brYt29fj2MO95oREQsWLIhSqdTxqKur+yRbAgAAjmJli6cdO3bEgQMHoqamptPxmpqaaG1t7XZOa2trt+P3798fO3bs6HHM4V4zIuKWW26Jtra2jsfWrVs/yZYAAICjWGW5v0FFRUWnr4ui6HLs48Z/9HhvX7OqqiqqqqrSawYAAPiosl15GjZsWAwYMKDLFaHt27d3uXJ0SG1tbbfjKysr44QTTuhxzOFeEwAAoC+ULZ4GDRoUDQ0NsWrVqk7HV61aFRMnTux2zoQJE7qMX7lyZYwbNy4GDhzY45jDvSYAAEBfKOuf7c2ePTuam5tj3LhxMWHChPjpT38aW7ZsienTp0fEB+9Feuutt+KXv/xlRHxwZ72FCxfG7Nmz47rrrouWlpZYvHhxp7vo3XjjjfG1r30t7rrrrrj88svjX//1X+Opp56K//iP/yjnVgAAgKNcWeNp2rRpsXPnzrj99ttj27ZtMXbs2Fi+fHmceuqpERGxbdu2Tp/5VF9fH8uXL49Zs2bFAw88ECNGjIj7778/pk6d2jFm4sSJ8dhjj8WPfvSj+Id/+Ic4/fTT4/HHH4/x48eXcysAAMBRrqyf83Sk6s293AEAgC+uI+JzngAAAL5IxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQIJ4AAAASxBMAAECCeAIAAEgQTwAAAAniCQAAIEE8AQAAJIgnAACABPEEAACQUNZ42rVrVzQ3N0epVIpSqRTNzc3x3nvv9TinKIqYN29ejBgxIo499ti48MIL49VXX+14/o9//GP84Ac/iFGjRsVxxx0Xp5xySsyYMSPa2trKuRUAAOAoV9Z4uvrqq2PDhg2xYsWKWLFiRWzYsCGam5t7nHP33XfHvffeGwsXLowXX3wxamtr4xvf+Ebs3r07IiLefvvtePvtt+Oee+6JjRs3xj/90z/FihUr4tprry3nVgAAgKNcRVEURTleeNOmTTFmzJhYu3ZtjB8/PiIi1q5dGxMmTIjf/e53MWrUqC5ziqKIESNGxMyZM+Pmm2+OiIg9e/ZETU1N3HXXXXH99dd3+71+/etfxzXXXBN/+tOforKy8mPX1t7eHqVSKdra2mLIkCGfYpcAAMDnWW/aoGxXnlpaWqJUKnWEU0TE+eefH6VSKdasWdPtnM2bN0dra2s0NTV1HKuqqooLLrjgsHMiomOjhwunPXv2RHt7e6cHAABAb5QtnlpbW2P48OFdjg8fPjxaW1sPOycioqamptPxmpqaw87ZuXNn3HHHHYe9KhURsWDBgo73XZVKpairq8tuAwAAICI+QTzNmzcvKioqenysW7cuIiIqKiq6zC+KotvjH/bR5w83p729Pb75zW/GmDFjYu7cuYd9vVtuuSXa2to6Hlu3bs1sFQAAoMPHv0HoI2644Ya48sorexwzcuTIeOWVV+Kdd97p8ty7777b5crSIbW1tRHxwRWoE088seP49u3bu8zZvXt3TJ48Ob785S/H0qVLY+DAgYddT1VVVVRVVfW4ZgAAgJ70Op6GDRsWw4YN+9hxEyZMiLa2tnjhhRfivPPOi4iI559/Ptra2mLixIndzqmvr4/a2tpYtWpVnHPOORERsXfv3li9enXcddddHePa29tj0qRJUVVVFcuWLYvq6urebgMAAKBXyvaepzPPPDMmT54c1113XaxduzbWrl0b1113XVxyySWd7rQ3evToWLp0aUR88Od6M2fOjPnz58fSpUvjP//zP+Nv//Zv47jjjourr746Ij644tTU1BR/+tOfYvHixdHe3h6tra3R2toaBw4cKNd2AACAo1yvrzz1xq9+9auYMWNGx93zLrvssli4cGGnMa+//nqnD7i96aab4s9//nN8//vfj127dsX48eNj5cqVMXjw4IiIeOmll+L555+PiIi/+Iu/6PRamzdvjpEjR5ZxRwAAwNGqbJ/zdCTzOU8AAEDEEfI5TwAAAF8k4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJZY2nXbt2RXNzc5RKpSiVStHc3Bzvvfdej3OKooh58+bFiBEj4thjj40LL7wwXn311cOOnTJlSlRUVMSTTz7Z9xsAAAD4f2WNp6uvvjo2bNgQK1asiBUrVsSGDRuiubm5xzl333133HvvvbFw4cJ48cUXo7a2Nr7xjW/E7t27u4y97777oqKiolzLBwAA6FBZrhfetGlTrFixItauXRvjx4+PiIhFixbFhAkT4vXXX49Ro0Z1mVMURdx3331x2223xbe+9a2IiPjFL34RNTU18c///M9x/fXXd4x9+eWX4957740XX3wxTjzxxHJtAwAAICLKeOWppaUlSqVSRzhFRJx//vlRKpVizZo13c7ZvHlztLa2RlNTU8exqqqquOCCCzrNef/99+Oqq66KhQsXRm1t7ceuZc+ePdHe3t7pAQAA0Btli6fW1tYYPnx4l+PDhw+P1tbWw86JiKipqel0vKamptOcWbNmxcSJE+Pyyy9PrWXBggUd77sqlUpRV1eX3QYAAEBEfIJ4mjdvXlRUVPT4WLduXUREt+9HKoriY9+n9NHnPzxn2bJl8fTTT8d9992XXvMtt9wSbW1tHY+tW7em5wIAAER8gvc83XDDDXHllVf2OGbkyJHxyiuvxDvvvNPluXfffbfLlaVDDv0JXmtra6f3MW3fvr1jztNPPx1/+MMf4vjjj+80d+rUqdHY2BjPPPNMl9etqqqKqqqqHtcMAADQk17H07Bhw2LYsGEfO27ChAnR1tYWL7zwQpx33nkREfH8889HW1tbTJw4sds59fX1UVtbG6tWrYpzzjknIiL27t0bq1evjrvuuisiIubMmRN/93d/12neWWedFT/5yU/i0ksv7e12AAAAUsp2t70zzzwzJk+eHNddd1384z/+Y0RE/P3f/31ccsklne60N3r06FiwYEH81V/9VVRUVMTMmTNj/vz5ccYZZ8QZZ5wR8+fPj+OOOy6uvvrqiPjg6lR3N4k45ZRTor6+vlzbAQAAjnJli6eIiF/96lcxY8aMjrvnXXbZZbFw4cJOY15//fVoa2vr+Pqmm26KP//5z/H9738/du3aFePHj4+VK1fG4MGDy7lUAACAHlUURVH09yI+a+3t7VEqlaKtrS2GDBnS38sBAAD6SW/aoGy3KgcAAPgiEU8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIEE8AAAAJ4gkAACBBPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgngCAABIqOzvBfSHoigiIqK9vb2fVwIAAPSnQ01wqBF6clTG0+7duyMioq6urp9XAgAAHAl2794dpVKpxzEVRSaxvmAOHjwYb7/9dgwePDgqKir6ezkcRnt7e9TV1cXWrVtjyJAh/b0cPgecM/SWc4becs7QW86ZI19RFLF79+4YMWJEHHNMz+9qOiqvPB1zzDFx8skn9/cySBoyZIhfNvSKc4becs7QW84Zess5c2T7uCtOh7hhBAAAQIJ4AgAASBBPHLGqqqpi7ty5UVVV1d9L4XPCOUNvOWfoLecMveWc+WI5Km8YAQAA0FuuPAEAACSIJwAAgATxBAAAkCCeAAAAEsQTAABAgnii3+zatSuam5ujVCpFqVSK5ubmeO+993qcUxRFzJs3L0aMGBHHHntsXHjhhfHqq68eduyUKVOioqIinnzyyb7fAJ+5cpwzf/zjH+MHP/hBjBo1Ko477rg45ZRTYsaMGdHW1lbm3VAODz74YNTX10d1dXU0NDTEs88+2+P41atXR0NDQ1RXV8dpp50WDz/8cJcxS5YsiTFjxkRVVVWMGTMmli5dWq7l0w/6+pxZtGhRNDY2xtChQ2Po0KFx0UUXxQsvvFDOLfAZK8fvmUMee+yxqKioiCuuuKKPV02fKaCfTJ48uRg7dmyxZs2aYs2aNcXYsWOLSy65pMc5d955ZzF48OBiyZIlxcaNG4tp06YVJ554YtHe3t5l7L333ltMmTKliIhi6dKlZdoFn6VynDMbN24svvWtbxXLli0rfv/73xf//u//XpxxxhnF1KlTP4st0Ycee+yxYuDAgcWiRYuK1157rbjxxhuLL33pS8Wbb77Z7fj/+q//Ko477rjixhtvLF577bVi0aJFxcCBA4vf/OY3HWPWrFlTDBgwoJg/f36xadOmYv78+UVlZWWxdu3az2pblFE5zpmrr766eOCBB4r169cXmzZtKr73ve8VpVKp+O///u/PaluUUTnOmUPeeOON4qSTTioaGxuLyy+/vMw74ZMST/SL1157rYiITv8D0tLSUkRE8bvf/a7bOQcPHixqa2uLO++8s+PY//7v/xalUql4+OGHO43dsGFDcfLJJxfbtm0TT18Q5T5nPuxf/uVfikGDBhX79u3ruw1Qduedd14xffr0TsdGjx5dzJkzp9vxN910UzF69OhOx66//vri/PPP7/j629/+djF58uROYyZNmlRceeWVfbRq+lM5zpmP2r9/fzF48ODiF7/4xadfMP2uXOfM/v37i7/8y78sfvaznxXf/e53xdMRzJ/t0S9aWlqiVCrF+PHjO46df/75USqVYs2aNd3O2bx5c7S2tkZTU1PHsaqqqrjgggs6zXn//ffjqquuioULF0ZtbW35NsFnqpznzEe1tbXFkCFDorKysu82QFnt3bs3XnrppU4/64iIpqamw/6sW1pauoyfNGlSrFu3Lvbt29fjmJ7OHz4fynXOfNT7778f+/bti6985St9s3D6TTnPmdtvvz2++tWvxrXXXtv3C6dPiSf6RWtrawwfPrzL8eHDh0dra+th50RE1NTUdDpeU1PTac6sWbNi4sSJcfnll/fhiulv5TxnPmznzp1xxx13xPXXX/8pV8xnaceOHXHgwIFe/axbW1u7Hb9///7YsWNHj2MO95p8fpTrnPmoOXPmxEknnRQXXXRR3yycflOuc+a5556LxYsXx6JFi8qzcPqUeKJPzZs3LyoqKnp8rFu3LiIiKioquswviqLb4x/20ec/PGfZsmXx9NNPx3333dc3G6Ls+vuc+bD29vb45je/GWPGjIm5c+d+il3RX7I/657Gf/R4b1+Tz5dynDOH3H333fHoo4/GE088EdXV1X2wWo4EfXnO7N69O6655ppYtGhRDBs2rO8XS5/zNyn0qRtuuCGuvPLKHseMHDkyXnnllXjnnXe6PPfuu+92+ReaQw79CV5ra2uceOKJHce3b9/eMefpp5+OP/zhD3H88cd3mjt16tRobGyMZ555phe74bPQ3+fMIbt3747JkyfHl7/85Vi6dGkMHDiwt1uhHw0bNiwGDBjQ5V9/u/tZH1JbW9vt+MrKyjjhhBN6HHO41+Tzo1znzCH33HNPzJ8/P5566qk4++yz+3bx9ItynDOvvvpqvPHGG3HppZd2PH/w4MGIiKisrIzXX389Tj/99D7eCZ+GK0/0qWHDhsXo0aN7fFRXV8eECROira2t0+1bn3/++Whra4uJEyd2+9r19fVRW1sbq1at6ji2d+/eWL16dcecOXPmxCuvvBIbNmzoeERE/OQnP4mf//zn5ds4n1h/nzMRH1xxampqikGDBsWyZcv8C/Hn0KBBg6KhoaHTzzoiYtWqVYc9PyZMmNBl/MqVK2PcuHEd8Xy4MYd7TT4/ynXORET8+Mc/jjvuuCNWrFgR48aN6/vF0y/Kcc6MHj06Nm7c2On/Wy677LL4+te/Hhs2bIi6urqy7YdPqJ9uVAHF5MmTi7PPPrtoaWkpWlpairPOOqvLbadHjRpVPPHEEx1f33nnnUWpVCqeeOKJYuPGjcVVV1112FuVHxLutveFUY5zpr29vRg/fnxx1llnFb///e+Lbdu2dTz279//me6PT+fQLYQXL15cvPbaa8XMmTOLL33pS8Ubb7xRFEVRzJkzp2hubu4Yf+gWwrNmzSpee+21YvHixV1uIfzcc88VAwYMKO68885i06ZNxZ133ulW5V8g5Thn7rrrrmLQoEHFb37zm06/T3bv3v2Z74++V45z5qPcbe/IJp7oNzt37iy+853vFIMHDy4GDx5cfOc73yl27drVaUxEFD//+c87vj548GAxd+7cora2tqiqqiq+9rWvFRs3buzx+4inL45ynDO//e1vi4jo9rF58+bPZmP0mQceeKA49dRTi0GDBhXnnntusXr16o7nvvvd7xYXXHBBp/HPPPNMcc455xSDBg0qRo4cWTz00ENdXvPXv/51MWrUqGLgwIHF6NGjiyVLlpR7G3yG+vqcOfXUU7v9fTJ37tzPYDd8Fsrxe+bDxNORraIo/v9dawAAAByW9zwBAAAkiCcAAIAE8QQAAJAgngAAABLEEwAAQIJ4AgAASBBPAAAACeIJAAAgQTwBAAAkiCcAAIAE8QQAAJDwfxNsDEgWmcV8AAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 1000x1000 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "fig, ax = plt.subplots(figsize=(10, 10))\n",
    "sns.histplot(data=coefficients, x='coefficient', ax=ax, bins=50, stat='density', kde=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
